<?php

/**
 * Color settings
 *
 * @var  array   any existing settings
 * @return array  existing sections + colors
 *
 */
function avada_options_section_colors( $sections ) {

	$light = array();
	$light['header_bg_color'] = '#ffffff';
	$light['header_border_color'] = '#e5e5e5';
	$light['content_bg_color'] = '#ffffff';
	$light['slidingbar_bg_color'] = '#363839';
	$light['header_sticky_bg_color'] = '#ffffff';
	$light['footer_bg_color'] = '#363839';
	$light['footer_border_color'] = '#e9eaee';
	$light['copyright_border_color'] = '#4B4C4D';
	$light['testimonial_bg_color'] = '#f6f3f3';
	$light['testimonial_text_color'] = '#747474';
	$light['sep_color'] = '#e0dede';
	$light['slidingbar_divider_color'] = '#505152';
	$light['footer_divider_color'] = '#505152';
	$light['form_bg_color'] = '#ffffff';
	$light['form_text_color'] = '#aaa9a9';
	$light['form_border_color'] = '#d2d2d2';
	$light['tagline_font_color'] = '#747474';
	$light['page_title_color'] = '#333333';
	$light['h1_typography']['color'] = '#333333';
	$light['h2_typography']['color'] = '#333333';
	$light['h3_typography']['color'] = '#333333';
	$light['h4_typography']['color'] = '#333333';
	$light['h5_typography']['color'] = '#333333';
	$light['h6_typography']['color'] = '#333333';
	$light['body_typography']['color'] = '#747474';
	$light['link_color'] = '#333333';
	$light['menu_h45_bg_color'] = '#FFFFFF';
	$light['menu_first_color'] = '#333333';
	$light['menu_sub_bg_color'] = '#f2efef';
	$light['menu_sub_color'] = '#333333';
	$light['menu_bg_hover_color'] = '#f8f8f8';
	$light['menu_sub_sep_color'] = '#dcdadb';
	$light['snav_color'] = '#ffffff';
	$light['header_social_links_icon_color'] = '#ffffff';
	$light['header_top_first_border_color'] = '#e5e5e5';
	$light['header_top_sub_bg_color'] = '#ffffff';
	$light['header_top_menu_sub_color'] = '#747474';
	$light['header_top_menu_bg_hover_color'] = '#fafafa';
	$light['header_top_menu_sub_hover_color'] = '#333333';
	$light['header_top_menu_sub_sep_color'] = '#e5e5e5';
	$light['sidebar_bg_color'] = '#ffffff';
	$light['page_title_bg_color'] = '#F6F6F6';
	$light['page_title_border_color'] = '#d2d3d4';
	$light['breadcrumbs_text_color'] = '#333333';
	$light['sidebar_heading_color'] = '#333333';
	$light['accordian_inactive_color'] = '#333333';
	$light['counter_filled_color'] = '#a0ce4e';
	$light['counter_unfilled_color'] = '#f6f6f6';
	$light['dates_box_color'] = '#eef0f2';
	$light['carousel_nav_color'] = '#999999';
	$light['carousel_hover_color'] = '#808080';
	$light['content_box_bg_color'] = 'transparent';
	$light['title_border_color'] = '#e0dede';
	$light['icon_circle_color'] = '#333333';
	$light['icon_border_color'] = '#333333';
	$light['icon_color'] = '#ffffff';
	$light['imgframe_border_color'] = '#f6f6f6';
	$light['imgframe_style_color'] = '#000000';
	$light['sep_pricing_box_heading_color'] = '#333333';
	$light['full_boxed_pricing_box_heading_color'] = '#333333';
	$light['pricing_bg_color'] = '#ffffff';
	$light['pricing_border_color'] = '#f8f8f8';
	$light['pricing_divider_color'] = '#ededed';
	$light['social_bg_color'] = '#f6f6f6';
	$light['tabs_bg_color'] = '#ffffff';
	$light['tabs_inactive_color'] = '#f1f2f2';
	$light['tagline_bg'] = '#f6f6f6';
	$light['tagline_border_color'] = '#f6f6f6';
	$light['timeline_bg_color'] = 'transparent';
	$light['timeline_color'] = '#ebeaea';
	$light['woo_cart_bg_color'] = '#fafafa';
	$light['qty_bg_color'] = '#fbfaf9';
	$light['qty_bg_hover_color'] = '#ffffff';
	$light['bbp_forum_header_bg'] = '#ebeaea';
	$light['bbp_forum_border_color'] = '#ebeaea';
	$light['checklist_icons_color'] = '#ffffff';
	$light['flip_boxes_front_bg'] = '#f6f6f6';
	$light['flip_boxes_front_heading'] = '#333333';
	$light['flip_boxes_front_text'] = '#747474';
	$light['full_width_bg_color'] = '#ffffff';
	$light['full_width_border_color'] = '#eae9e9';
	$light['modal_bg_color'] = '#f6f6f6';
	$light['modal_border_color'] = '#ebebeb';
	$light['person_border_color'] = '#f6f6f6';
	$light['popover_heading_bg_color'] = '#f6f6f6';
	$light['popover_content_bg_color'] = '#ffffff';
	$light['popover_border_color'] = '#ebebeb';
	$light['popover_text_color'] = '#747474';
	$light['progressbar_unfilled_color'] = '#f6f6f6';
	$light['section_sep_bg'] = '#f6f6f6';
	$light['section_sep_border_color'] = '#f6f6f6';
	$light['sharing_box_tagline_text_color'] = '#333333';
	$light['header_social_links_icon_color'] = '#bebdbd';
	$light['header_social_links_box_color'] = '#e8e8e8';
	$light['bg_color'] = '#d7d6d6';
	$light['mobile_menu_background_color'] = '#f9f9f9';
	$light['mobile_menu_border_color'] = '#dadada';
	$light['mobile_menu_hover_color'] = '#f6f6f6';
	$light['social_links_icon_color'] = '#bebdbd';
	$light['social_links_box_color'] = '#e8e8e8';
	$light['sharing_social_links_icon_color'] = '#bebdbd';
	$light['sharing_social_links_box_color'] = '#e8e8e8';
	$light['load_more_posts_button_bg_color'] = '#ebeaea';
	$light['ec_bar_bg_color'] = '#efeded';
	$light['flyout_menu_icon_color'] = '#333333';
	$light['flyout_menu_background_color'] = 'rgba(255,255,255,0.95)';

	$dark = array();
	$dark['header_bg_color'] = '#29292a';
	$dark['header_border_color'] = '#3e3e3e';
	$dark['header_top_bg_color'] = '#29292a';
	$dark['content_bg_color'] = '#29292a';
	$dark['slidingbar_bg_color'] = '#363839';
	$dark['header_sticky_bg_color'] = '#29292a';
	$dark['slidingbar_border_color'] = '#484747';
	$dark['footer_bg_color'] = '#2d2d2d';
	$dark['footer_border_color'] = '#403f3f';
	$dark['copyright_border_color'] = '#4B4C4D';
	$dark['testimonial_bg_color'] = '#3e3e3e';
	$dark['testimonial_text_color'] = '#aaa9a9';
	$dark['sep_color'] = '#3e3e3e';
	$dark['slidingbar_divider_color'] = '#505152';
	$dark['footer_divider_color'] = '#505152';
	$dark['form_bg_color'] = '#3e3e3e';
	$dark['form_text_color'] = '#cccccc';
	$dark['form_border_color'] = '#212122';
	$dark['tagline_font_color'] = '#ffffff';
	$dark['page_title_color'] = '#ffffff';
	$dark['h1_typography']['color'] = '#ffffff';
	$dark['h2_typography']['color'] = '#ffffff';
	$dark['h3_typography']['color'] = '#ffffff';
	$dark['h4_typography']['color'] = '#ffffff';
	$dark['h5_typography']['color'] = '#ffffff';
	$dark['h6_typography']['color'] = '#ffffff';
	$dark['body_typography']['color'] = '#aaa9a9';
	$dark['link_color'] = '#ffffff';
	$dark['menu_h45_bg_color'] = '#29292A';
	$dark['menu_first_color'] = '#ffffff';
	$dark['menu_sub_bg_color'] = '#3e3e3e';
	$dark['menu_sub_color'] = '#d6d6d6';
	$dark['menu_bg_hover_color'] = '#383838';
	$dark['menu_sub_sep_color'] = '#313030';
	$dark['snav_color'] = '#747474';
	$dark['header_social_links_icon_color'] = '#747474';
	$dark['header_top_first_border_color'] = '#3e3e3e';
	$dark['header_top_sub_bg_color'] = '#29292a';
	$dark['header_top_menu_sub_color'] = '#d6d6d6';
	$dark['header_top_menu_bg_hover_color'] = '#333333';
	$dark['header_top_menu_sub_hover_color'] = '#d6d6d6';
	$dark['header_top_menu_sub_sep_color'] = '#3e3e3e';
	$dark['sidebar_bg_color'] = '#29292a';
	$dark['page_title_bg_color'] = '#353535';
	$dark['page_title_border_color'] = '#464646';
	$dark['breadcrumbs_text_color'] = '#ffffff';
	$dark['sidebar_heading_color'] = '#ffffff';
	$dark['accordian_inactive_color'] = '#3e3e3e';
	$dark['counter_filled_color'] = '#a0ce4e';
	$dark['counter_unfilled_color'] = '#3e3e3e';
	$dark['dates_box_color'] = '#3e3e3e';
	$dark['carousel_nav_color'] = '#3a3a3a';
	$dark['carousel_hover_color'] = '#333333';
	$dark['content_box_bg_color'] = 'transparent';
	$dark['title_border_color'] = '#3e3e3e';
	$dark['icon_circle_color'] = '#3e3e3e';
	$dark['icon_border_color'] = '#3e3e3e';
	$dark['icon_color'] = '#ffffff';
	$dark['imgframe_border_color'] = '#494848';
	$dark['imgframe_style_color'] = '#000000';
	$dark['sep_pricing_box_heading_color'] = '#ffffff';
	$dark['full_boxed_pricing_box_heading_color'] = '#AAA9A9';
	$dark['pricing_bg_color'] = '#3e3e3e';
	$dark['pricing_border_color'] = '#353535';
	$dark['pricing_divider_color'] = '#29292a';
	$dark['social_bg_color'] = '#3e3e3e';
	$dark['tabs_bg_color'] = '#3e3e3e';
	$dark['tabs_inactive_color'] = '#313132';
	$dark['tagline_bg'] = '#3e3e3e';
	$dark['tagline_border_color'] = '#3e3e3e';
	$dark['timeline_bg_color'] = 'transparent';
	$dark['timeline_color'] = '#3e3e3e';
	$dark['woo_cart_bg_color'] = '#333333';
	$dark['qty_bg_color'] = '#29292a';
	$dark['qty_bg_hover_color'] = '#383838';
	$dark['bbp_forum_header_bg'] = '#383838';
	$dark['bbp_forum_border_color'] = '#212121';
	$dark['checklist_icons_color'] = '#ffffff';
	$dark['flip_boxes_front_bg'] = '#3e3e3e';
	$dark['flip_boxes_front_heading'] = '#ffffff';
	$dark['flip_boxes_front_text'] = '#aaa9a9';
	$dark['full_width_bg_color'] = '#242424';
	$dark['full_width_border_color'] = '#3e3e3e';
	$dark['modal_bg_color'] = '#29292a';
	$dark['modal_border_color'] = '#242424';
	$dark['person_border_color'] = '#494848';
	$dark['popover_heading_bg_color'] = '#29292a';
	$dark['popover_content_bg_color'] = '#3e3e3e';
	$dark['popover_border_color'] = '#242424';
	$dark['popover_text_color'] = '#ffffff';
	$dark['progressbar_unfilled_color'] = '#3e3e3e';
	$dark['section_sep_bg'] = '#3e3e3e';
	$dark['section_sep_border_color'] = '#3e3e3e';
	$dark['sharing_box_tagline_text_color'] = '#ffffff';
	$dark['header_social_links_icon_color'] = '#545455';
	$dark['header_social_links_box_color'] = '#383838';
	$dark['bg_color'] = '#1e1e1e';
	$dark['mobile_menu_background_color'] = '#3e3e3e';
	$dark['mobile_menu_border_color'] = '#212122';
	$dark['mobile_menu_hover_color'] = '#383737';
	$dark['social_links_icon_color'] = '#3e3e3e';
	$dark['social_links_box_color'] = '#383838';
	$dark['sharing_social_links_icon_color'] = '#919191';
	$dark['sharing_social_links_box_color'] = '#4b4e4f';
	$dark['load_more_posts_button_bg_color'] = '#3e3e3e';
	$dark['ec_bar_bg_color'] = '#353535';
	$dark['flyout_menu_icon_color'] = '#ffffff';
	$dark['flyout_menu_background_color'] = 'rgba(0,0,0,0.85)';

	$green = array();
	$green['primary_color'] = '#a0ce4e';
	$green['pricing_box_color'] = '#92C563';
	$green['image_gradient_top_color'] = '#D1E990';
	$green['image_gradient_bottom_color'] = '#AAD75B';
	$green['button_gradient_top_color'] = '#D1E990';
	$green['button_gradient_bottom_color'] = '#AAD75B';
	$green['button_gradient_top_color_hover'] = '#AAD75B';
	$green['button_gradient_bottom_color_hover'] = '#D1E990';
	$green['button_accent_color'] = '#6e9a1f';
	$green['button_accent_hover_color'] = '#638e1a';
	$green['button_bevel_color'] = '#54770f';
	$green['checklist_circle_color'] = '#a0ce4e';
	$green['counter_box_color'] = '#a0ce4e';
	$green['countdown_background_color'] = '#a0ce4e';
	$green['dropcap_color'] = '#a0ce4e';
	$green['flip_boxes_back_bg'] = '#a0ce4e';
	$green['progressbar_filled_color'] = '#a0ce4e';
	$green['counter_filled_color'] = '#a0ce4e';
	$green['ec_sidebar_widget_bg_color'] = '#a0ce4e';
	$green['menu_hover_first_color'] = '#a0ce4e';
	$green['header_top_bg_color'] = '#a0ce4e';
	$green['content_box_hover_animation_accent_color'] = '#a0ce4e';
	$green['map_overlay_color'] = '#a0ce4e';
	$green['flyout_menu_icon_hover_color'] = '#a0ce4e';

	$darkgreen = array();
	$darkgreen['primary_color'] = '#9db668';
	$darkgreen['pricing_box_color'] = '#a5c462';
	$darkgreen['image_gradient_top_color'] = '#cce890';
	$darkgreen['image_gradient_bottom_color'] = '#afd65a';
	$darkgreen['button_gradient_top_color'] = '#cce890';
	$darkgreen['button_gradient_bottom_color'] = '#AAD75B';
	$darkgreen['button_gradient_top_color_hover'] = '#AAD75B';
	$darkgreen['button_gradient_bottom_color_hover'] = '#cce890';
	$darkgreen['button_accent_color'] = '#577810';
	$darkgreen['button_accent_hover_color'] = '#577810';
	$darkgreen['button_bevel_color'] = '#577810';
	$darkgreen['checklist_circle_color'] = '#9db668';
	$darkgreen['counter_box_color'] = '#9db668';
	$darkgreen['countdown_background_color'] = '#9db668';
	$darkgreen['dropcap_color'] = '#9db668';
	$darkgreen['flip_boxes_back_bg'] = '#9db668';
	$darkgreen['progressbar_filled_color'] = '#9db668';
	$darkgreen['counter_filled_color'] = '#9db668';
	$darkgreen['ec_sidebar_widget_bg_color'] = '#9db668';
	$darkgreen['menu_hover_first_color'] = '#9db668';
	$darkgreen['header_top_bg_color'] = '#9db668';
	$darkgreen['content_box_hover_animation_accent_color'] = '#9db668';
	$darkgreen['map_overlay_color'] = '#9db668';
	$darkgreen['flyout_menu_icon_hover_color'] = '#9db668';

	$orange = array();
	$orange['primary_color'] = '#e9a825';
	$orange['pricing_box_color'] = '#c4a362';
	$orange['image_gradient_top_color'] = '#e8cb90';
	$orange['image_gradient_bottom_color'] = '#d6ad5a';
	$orange['button_gradient_top_color'] = '#e8cb90';
	$orange['button_gradient_bottom_color'] = '#d6ad5a';
	$orange['button_gradient_top_color_hover'] = '#d6ad5a';
	$orange['button_gradient_bottom_color_hover'] = '#e8cb90';
	$orange['button_accent_color'] = '#785510';
	$orange['button_accent_hover_color'] = '#785510';
	$orange['button_bevel_color'] = '#785510';
	$orange['checklist_circle_color'] = '#e9a825';
	$orange['counter_box_color'] = '#e9a825';
	$orange['countdown_background_color'] = '#e9a825';
	$orange['dropcap_color'] = '#e9a825';
	$orange['flip_boxes_back_bg'] = '#e9a825';
	$orange['progressbar_filled_color'] = '#e9a825';
	$orange['counter_filled_color'] = '#e9a825';
	$orange['ec_sidebar_widget_bg_color'] = '#e9a825';
	$orange['menu_hover_first_color'] = '#e9a825';
	$orange['header_top_bg_color'] = '#e9a825';
	$orange['content_box_hover_animation_accent_color'] = '#e9a825';
	$orange['map_overlay_color'] = '#e9a825';
	$orange['flyout_menu_icon_hover_color'] = '#e9a825';

	$lightblue = array();
	$lightblue['primary_color'] = '#67b7e1';
	$lightblue['pricing_box_color'] = '#62a2c4';
	$lightblue['image_gradient_top_color'] = '#90c9e8';
	$lightblue['image_gradient_bottom_color'] = '#5aabd6';
	$lightblue['button_gradient_top_color'] = '#90c9e8';
	$lightblue['button_gradient_bottom_color'] = '#5aabd6';
	$lightblue['button_gradient_top_color_hover'] = '#5aabd6';
	$lightblue['button_gradient_bottom_color_hover'] = '#90c9e8';
	$lightblue['button_accent_color'] = '#105378';
	$lightblue['button_accent_hover_color'] = '#105378';
	$lightblue['button_bevel_color'] = '#105378';
	$lightblue['checklist_circle_color'] = '#67b7e1';
	$lightblue['counter_box_color'] = '#67b7e1';
	$lightblue['countdown_background_color'] = '#67b7e1';
	$lightblue['dropcap_color'] = '#67b7e1';
	$lightblue['flip_boxes_back_bg'] = '#67b7e1';
	$lightblue['progressbar_filled_color'] = '#67b7e1';
	$lightblue['counter_filled_color'] = '#67b7e1';
	$lightblue['ec_sidebar_widget_bg_color'] = '#67b7e1';
	$lightblue['menu_hover_first_color'] = '#67b7e1';
	$lightblue['header_top_bg_color'] = '#67b7e1';
	$lightblue['content_box_hover_animation_accent_color'] = '#67b7e1';
	$lightblue['map_overlay_color'] = '#67b7e1';
	$lightblue['flyout_menu_icon_hover_color'] = '#67b7e1';

	$lightred = array();
	$lightred['primary_color'] = '#f05858';
	$lightred['pricing_box_color'] = '#c46262';
	$lightred['image_gradient_top_color'] = '#e89090';
	$lightred['image_gradient_bottom_color'] = '#d65a5a';
	$lightred['button_gradient_top_color'] = '#e89090';
	$lightred['button_gradient_bottom_color'] = '#d65a5a';
	$lightred['button_gradient_top_color_hover'] = '#d65a5a';
	$lightred['button_gradient_bottom_color_hover'] = '#e89090';
	$lightred['button_accent_color'] = '#781010';
	$lightred['button_accent_hover_color'] = '#781010';
	$lightred['button_bevel_color'] = '#781010';
	$lightred['checklist_circle_color'] = '#f05858';
	$lightred['counter_box_color'] = '#f05858';
	$lightred['countdown_background_color'] = '#f05858';
	$lightred['dropcap_color'] = '#f05858';
	$lightred['flip_boxes_back_bg'] = '#f05858';
	$lightred['progressbar_filled_color'] = '#f05858';
	$lightred['counter_filled_color'] = '#f05858';
	$lightred['ec_sidebar_widget_bg_color'] = '#f05858';
	$lightred['menu_hover_first_color'] = '#f05858';
	$lightred['header_top_bg_color'] = '#f05858';
	$lightred['content_box_hover_animation_accent_color'] = '#f05858';
	$lightred['map_overlay_color'] = '#f05858';
	$lightred['flyout_menu_icon_hover_color'] = '#f05858';

	$pink = array();
	$pink['primary_color'] = '#e67fb9';
	$pink['pricing_box_color'] = '#c46299';
	$pink['image_gradient_top_color'] = '#e890c2';
	$pink['image_gradient_bottom_color'] = '#d65aa0';
	$pink['button_gradient_top_color'] = '#e890c2';
	$pink['button_gradient_bottom_color'] = '#d65aa0';
	$pink['button_gradient_top_color_hover'] = '#d65aa0';
	$pink['button_gradient_bottom_color_hover'] = '#e890c2';
	$pink['button_accent_color'] = '#78104b';
	$pink['button_accent_hover_color'] = '#78104b';
	$pink['button_bevel_color'] = '#78104b';
	$pink['checklist_circle_color'] = '#e67fb9';
	$pink['counter_box_color'] = '#e67fb9';
	$pink['countdown_background_color'] = '#e67fb9';
	$pink['dropcap_color'] = '#e67fb9';
	$pink['flip_boxes_back_bg'] = '#e67fb9';
	$pink['progressbar_filled_color'] = '#e67fb9';
	$pink['counter_filled_color'] = '#e67fb9';
	$pink['ec_sidebar_widget_bg_color'] = '#e67fb9';
	$pink['menu_hover_first_color'] = '#e67fb9';
	$pink['header_top_bg_color'] = '#e67fb9';
	$pink['content_box_hover_animation_accent_color'] = '#e67fb9';
	$pink['map_overlay_color'] = '#e67fb9';
	$pink['flyout_menu_icon_hover_color'] = '#e67fb9';

	$lightgrey = array();
	$lightgrey['primary_color'] = '#9e9e9e';
	$lightgrey['pricing_box_color'] = '#c4c4c4';
	$lightgrey['image_gradient_top_color'] = '#e8e8e8';
	$lightgrey['image_gradient_bottom_color'] = '#d6d6d6';
	$lightgrey['button_gradient_top_color'] = '#e8e8e8';
	$lightgrey['button_gradient_bottom_color'] = '#d6d6d6';
	$lightgrey['button_gradient_top_color_hover'] = '#d6d6d6';
	$lightgrey['button_gradient_bottom_color_hover'] = '#e8e8e8';
	$lightgrey['button_accent_color'] = '#787878';
	$lightgrey['button_accent_hover_color'] = '#787878';
	$lightgrey['button_bevel_color'] = '#787878';
	$lightgrey['checklist_circle_color'] = '#9e9e9e';
	$lightgrey['counter_box_color'] = '#9e9e9e';
	$lightgrey['countdown_background_color'] = '#9e9e9e';
	$lightgrey['dropcap_color'] = '#9e9e9e';
	$lightgrey['flip_boxes_back_bg'] = '#9e9e9e';
	$lightgrey['progressbar_filled_color'] = '#9e9e9e';
	$lightgrey['counter_filled_color'] = '#9e9e9e';
	$lightgrey['ec_sidebar_widget_bg_color'] = '#9e9e9e';
	$lightgrey['menu_hover_first_color'] = '#9e9e9e';
	$lightgrey['header_top_bg_color'] = '#9e9e9e';
	$lightgrey['content_box_hover_animation_accent_color'] = '#9e9e9e';
	$lightgrey['map_overlay_color'] = '#9e9e9e';
	$lightgrey['flyout_menu_icon_hover_color'] = '#9e9e9e';

	$brown = array();
	$brown['primary_color'] = '#ab8b65';
	$brown['pricing_box_color'] = '#c49862';
	$brown['image_gradient_top_color'] = '#e8c090';
	$brown['image_gradient_bottom_color'] = '#d69e5a';
	$brown['button_gradient_top_color'] = '#e8c090';
	$brown['button_gradient_bottom_color'] = '#d69e5a';
	$brown['button_gradient_top_color_hover'] = '#d69e5a';
	$brown['button_gradient_bottom_color_hover'] = '#e8c090';
	$brown['button_accent_color'] = '#784910';
	$brown['button_accent_hover_color'] = '#784910';
	$brown['button_bevel_color'] = '#784910';
	$brown['checklist_circle_color'] = '#ab8b65';
	$brown['counter_box_color'] = '#ab8b65';
	$brown['countdown_background_color'] = '#ab8b65';
	$brown['dropcap_color'] = '#ab8b65';
	$brown['flip_boxes_back_bg'] = '#ab8b65';
	$brown['progressbar_filled_color'] = '#ab8b65';
	$brown['ec_sidebar_widget_bg_color'] = '#ab8b65';
	$brown['menu_hover_first_color'] = '#ab8b65';
	$brown['header_top_bg_color'] = '#ab8b65';
	$brown['content_box_hover_animation_accent_color'] = '#ab8b65';
	$brown['map_overlay_color'] = '#ab8b65';
	$brown['flyout_menu_icon_hover_color'] = '#ab8b65';

	$red = array();
	$red['primary_color'] = '#e10707';
	$red['pricing_box_color'] = '#c40606';
	$red['image_gradient_top_color'] = '#e80707';
	$red['image_gradient_bottom_color'] = '#d60707';
	$red['button_gradient_top_color'] = '#e80707';
	$red['button_gradient_bottom_color'] = '#d60707';
	$red['button_gradient_top_color_hover'] = '#d60707';
	$red['button_gradient_bottom_color_hover'] = '#e80707';
	$red['button_accent_color'] = '#780404';
	$red['button_accent_hover_color'] = '#780404';
	$red['button_bevel_color'] = '#780404';
	$red['checklist_circle_color'] = '#e10707';
	$red['counter_box_color'] = '#e10707';
	$red['countdown_background_color'] = '#e10707';
	$red['dropcap_color'] = '#e10707';
	$red['flip_boxes_back_bg'] = '#e10707';
	$red['progressbar_filled_color'] = '#e10707';
	$red['counter_filled_color'] = '#e10707';
	$red['ec_sidebar_widget_bg_color'] = '#e10707';
	$red['menu_hover_first_color'] = '#e10707';
	$red['header_top_bg_color'] = '#e10707';
	$red['content_box_hover_animation_accent_color'] = '#e10707';
	$red['map_overlay_color'] = '#e10707';
	$red['flyout_menu_icon_hover_color'] = '#e10707';

	$blue = array();
	$blue['primary_color'] = '#1a80b6';
	$blue['pricing_box_color'] = '#62a2c4';
	$blue['image_gradient_top_color'] = '#90c9e8';
	$blue['image_gradient_bottom_color'] = '#5aabd6';
	$blue['button_gradient_top_color'] = '#90c9e8';
	$blue['button_gradient_bottom_color'] = '#5aabd6';
	$blue['button_gradient_top_color_hover'] = '#5aabd6';
	$blue['button_gradient_bottom_color_hover'] = '#90c9e8';
	$blue['button_accent_color'] = '#105378';
	$blue['button_accent_hover_color'] = '#105378';
	$blue['button_bevel_color'] = '#105378';
	$blue['checklist_circle_color'] = '#1a80b6';
	$blue['counter_box_color'] = '#1a80b6';
	$blue['countdown_background_color'] = '#1a80b6';
	$blue['dropcap_color'] = '#1a80b6';
	$blue['flip_boxes_back_bg'] = '#1a80b6';
	$blue['progressbar_filled_color'] = '#1a80b6';
	$blue['counter_filled_color'] = '#1a80b6';
	$blue['ec_sidebar_widget_bg_color'] = '#1a80b6';
	$blue['menu_hover_first_color'] = '#1a80b6';
	$blue['header_top_bg_color'] = '#1a80b6';
	$blue['content_box_hover_animation_accent_color'] = '#1a80b6';
	$blue['map_overlay_color'] = '#1a80b6';
	$blue['flyout_menu_icon_hover_color'] = '#1a80b6';

	$sections['colors'] = array(
		'label'    => esc_html__( 'Colors', 'Avada' ),
		'id'       => 'colors_section',
		'priority' => 3,
		'icon'     => 'el-icon-brush',
		'fields'   => array(
			'colors_important_note_info' => array(
				'label'       => '',
				'description' => '<div class="avada-avadaredux-important-notice">' . __( '<strong>IMPORTANT NOTE:</strong> This tab contains general color options. Additional color options for specific areas, can be found within other tabs. Example: For menu color options go to the menu tab.', 'Avada' ) . '</div>',
				'id'          => 'colors_important_note_info',
				'type'        => 'custom',
			),
			'scheme_type' => array(
				'label'       => esc_html__( 'Predefined Theme Skin', 'Avada' ),
				'description' => esc_html__( 'Controls the main theme skin to be light or dark. Select a skin and all color options will change to the defined selection.', 'Avada' ),
				'id'          => 'scheme_type',
				'default'     => '',
				'type'        => 'preset',
				'choices'     => array(
					'Light' => array(
						'label'    => esc_html__( 'Light', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/ffffff.png',
						'settings' => $light,
					),
					'Dark' => array(
						'label'    => esc_html__( 'Dark', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/29292a.png',
						'settings' => $dark,
					),
				),
			),
			'color_scheme' => array(
				'label'       => esc_html__( 'Predefined Color Scheme', 'Avada' ),
				'description' => esc_html__( 'Controls the main color scheme throughout the theme. Select a scheme and all color options will change to the defined selection.', 'Avada' ),
				'id'          => 'color_scheme',
				'default'     => 'Green',
				'type'        => 'preset',
				'choices'     => array(
					'Red'        => array(
						'label'    => esc_html__( 'Red', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/e10707.png',
						'settings' => $red,
					),
					'Light Red'  => array(
						'label'    => esc_html__( 'Light Red', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/f05858.png',
						'settings' => $lightred,
					),
					'Blue'       => array(
						'label'    => esc_html__( 'Blue', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/1a80b6.png',
						'settings' => $blue,
					),
					'Light Blue' => array(
						'label'    => esc_html__( 'Light Blue', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/67b7e1.png',
						'settings' => $lightblue,
					),
					'Green'      => array(
						'label'    => esc_html__( 'Green', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/a0ce4e.png',
						'settings' => $green,
					),
					'Dark Green' => array(
						'label'    => esc_html__( 'Dark Green', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/9db668.png',
						'settings' => $darkgreen,
					),
					'Orange'     => array(
						'label'    => esc_html__( 'Orange', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/e9a825.png',
						'settings' => $orange,
					),
					'Pink'       => array(
						'label'    => esc_html__( 'Pink', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/e67fb9.png',
						'settings' => $pink,
					),
					'Brown'      => array(
						'label'    => esc_html__( 'Brown', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/ab8b65.png',
						'settings' => $brown,
					),
					'Light Grey' => array(
						'label'    => esc_html__( 'Light Grey', 'Avada' ),
						'image'    => get_template_directory_uri().'/assets/images/colors/9e9e9e.png',
						'settings' => $lightgrey,
					),
				),
			),
			'primary_color' => array(
				'label'       => esc_html__( 'Primary Color', 'Avada' ),
				'description' => esc_html__( 'Controls the main highlight color throughout the theme.', 'Avada' ),
				'id'          => 'primary_color',
				'default'     => '#a0ce4e',
				'type'        => 'color',
			),
		),
	);

	return $sections;

}
